@extends('web.layouts.layout')

@section('breadcrumb')
    
    <span>Terms and Conditions</span>
    
@stop

@section('content')

<h2>Terms & Conditions</h2>
    <div class="post_container">
    <p>[ WWW.THEUML.COM ] ([ WWW.THEUML.COM ]) is a public access general purpose portfolio hosting web site and community for, actors, Singers and agencies. [ WWW.THEUML.COM ] provides a hosting service for person to person display, marketing, and communication on a professional level between models and photographers and agents. [ WWW.THEUML.COM ] does not own or claim to own any personal portfolio content or/and images uploaded by individual users for individual promotion and presentation. It is the responsibility of the user to abide by this agreement and site guidelines.</p>
<p>By using [ WWW.THEUML.COM ] you agree to the following terms and conditions that govern all of its members and site users. You also agreed to this contract between you, the user, and [ WWW.THEUML.COM ] when you clicked the &ldquo;I agree&rdquo; box during signup or if you are a non-member browsing [ WWW.THEUML.COM ].</p>
<p>Disclaimer: The service and the site contain information, facts and opinions from various individuals and organizations. THE SERVICE AND THE SITE ARE PROVIDED ON AN &ldquo;AS IS&rdquo; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OTHER THAN THOSE WARRANTIES WHICH ARE IMPOSED BY AND INCAPABLE OF EXCLUSION, RESTRICTION OR MODIFICATION UNDER THE LAWS APPLICABLE TO THIS AGREEMENT. NEITHER [ WWW.THEUML.COM ] NOR ITS AFFILIATES ENDORSE OR ARE RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF ANY OPINION, CASTING, JOB OFFER, ADVICE OR STATEMENT ON THE SERVICE OR THE SITES.</p>
<p>In accordance with the Children&rsquo;s Online Privacy Protection Rule you as the parent or guardian of a minor under the age of 16 have read and agree to the terms of use and take full responsibility for the minor based on the information below. [ WWW.THEUML.COM ], collects each e-mail, address, telephone number, age, height, weight, shoe size, physique, hair color, and eye color for children 16 and under directly through the [ WWW.THEUML.COM ] sign-up page. The child&rsquo;s telephone number, e-mail and exact address are not displayed publicly, only the major city location, height, weight, age, hair color, and eye color are displayed publicly for the purposes of casting agents to view and contact the child for castings.</p>
<p>[ WWW.THEUML.COM ] will never require disclosing more information than is reasonably necessary to participate in an activity as a condition of participation. Agents, as a third party, may request information for a casting; [ WWW.THEUML.COM ] will not make this information available to agents without first receiving permission from you via e-mail. [ WWW.THEUML.COM ] is not responsible for or liable to the actions of these agents who are not under any contract or agreement with [ WWW.THEUML.COM ] other than the terms and conditions set forth here. You can review the personal information, ask to have it deleted and refuse to allow any further collection or use of the information. Just e-mail customer.service@[ WWW.THEUML.COM ] with such requests.</p>
<p>The service and the site include portfolio booking forms, bulletin boards, forums, member messages, member comments which allow you and other users to post information, provide feedback to [ WWW.THEUML.COM ] and its affiliates, and interact in real-time. You agree not to post or transmit any unlawful, fake, fraudulent, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, profane, hateful, racially, ethnically or otherwise objectionable material of any kind, including, but not limited to, any material which encourages conduct that would constitute a criminal offense, violate the rights of others, or otherwise violate any applicable local, state, national or international law. Any content posted in the member messages as a casting or otherwise is done solely by the user, and is the full responsibility of the user and any and all recipients.</p>
<p>No member&rsquo;s e-mail address is made public through the member messages, if an e-mail is posted in the member message it is done so without the approval of [ WWW.THEUML.COM ] and against the messaging policies. Any acceptance, correspondence or agreement is solely the user&rsquo;s and recipient&rsquo;s responsibility. [ WWW.THEUML.COM ] divisions, affiliates, agents, representatives or licensors make no representation as to the legitimacy of any agency and they shall not be liable to anyone for any loss, injury, direct or indirect, incidental, consequential, special, punitive, or similar damages arising from information received or sent, either directly or indirectly through the member messages. In addition you agree to not post information or correspondence that is not of a professional nature or which contravenes US Federal, and International Trademark or copyright laws and restrictions in any way.</p>
<p>You will be responsible for, and indemnify and hold harmless [ WWW.THEUML.COM ], its subsidiaries, divisions, affiliates, agents and representatives against, any claim arising from any material that you post or transmit. Although [ WWW.THEUML.COM ] and its affiliates may from time to time monitor or review discussions, chats, postings, transmissions and bulletin boards on the site, neither [ WWW.THEUML.COM ] nor its affiliates is under any obligation to do so. [ WWW.THEUML.COM ] reserves the right to change or modify portfolio information or message board postings as needed and without notice. You acknowledge that [ WWW.THEUML.COM ] and its affiliates do not control the information available on the bulletin boards and that any opinions, advice, statements, services, offers or other information or content presented or disseminated on any bulletin board are those of their respective authors who are solely liable for their content. [ WWW.THEUML.COM ] and its affiliates reserve the right, at their sole discretion, to edit, refuse to post, or remove any material, links, email addresses, images, and content submitted to, or posted on bulletin boards, or portfolios. [ WWW.THEUML.COM ] and its affiliates reserve the right, in their sole discretion, to deny access to the e-mail systems provided for general community use.</p>
<p>[ WWW.THEUML.COM ] has guidelines regarding posting of appropriate images, email addresses, content, and links. You agree to read and adhere to the guidelines as posted throughout the site. Your use of the service and the sites is at your own risk. NEITHER GLAMHUNT NOR ANY OF ITS SUBSIDIARIES, DIVISIONS, AFFILIATES, AGENTS, REPRESENTATIVES OR LICENSORS SHALL BE LIABLE TO YOU OR ANYONE ELSE FOR ANY LOSS OR INJURY OR ANY DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE OR SIMILAR DAMAGES ARISING OUT OF YOUR ACCESS OR USE OF, OR YOUR INABILITY TO ACCESS OR USE, THE SERVICE AND THE SITES AND THE INFORMATION AVAILABLE ON THE SERVICE AND THE SITES OR ARISING OUT OF ANY ACTION TAKEN IN RESPONSE TO OR AS A RESULT OF ANY INFORMATION AVAILABLE ON THE SERVICE AND THE SITES. YOU HEREBY WAIVE ANY AND ALL CLAIMS AGAINST [ WWW.THEUML.COM ] AND ITS SUBSIDIARIES, DIVISIONS, AFFILIATES, AGENTS, REPRESENTATIVES AND LICENSORS ARISING OUT OF YOUR USE OF THE SERVICE AND THE SITES AND THE INFORMATION AVAILABLE THEREOF. DUE TO THE INSTANT-ACCESS NATURE OF THE [ WWW.THEUML.COM ] WEB SITE AND SERVICE, [ WWW.THEUML.COM ] WILL NOT BE RESPONSIBLE FOR REFUNDING ANY PAYPAL PAYMENTS OR WITHDRAWS. IT IS THE RESPONSIBILITY OF THE USER TO CANCEL FUTURE PAYMENTS IN THEIR PAYPAL ACCOUNT AS PER INSTRUCTIONS POSTED. YOU HEREBY WAIVE ANY AND ALL CLAIMS AGAINST PAYPAL AND [ WWW.THEUML.COM ] AND THEIR SUBSIDIARIES, DIVISIONS, AFFILIATES, AGENTS, REPRESENTATIVES AND LICENSORS FOR PAYMENTS AND/OR COMPENSATION CLAIMS ARISING OUT OF YOUR USE OF THE SERVICE AND THE SITES AND THE INFORMATION AVAILABLE THEREOF.</p>
<p>Any communication or material you post or transmit to the service and/or the site is, and will be treated as, non-confidential and non-proprietary. You assume full responsibility for anything you post or transmit, and you grant [ WWW.THEUML.COM ] and its affiliates the right to edit, copy, publish and distribute any information or content you post or transmit for any purpose.</p>
<p>[ WWW.THEUML.COM ] and its affiliates do not review or monitor any web sites linked to the service or from personal portfolios on this site. When clicking links to personal pages from [ WWW.THEUML.COM ] all users of the system acknowledge that [ WWW.THEUML.COM ] is not responsible for the accuracy or content of those links. You agree to not post URLs and other web links in any form, into your personal home page section, or the main portfolio page as links or text, that lead to ADULT SITES or Pay Sites. [ WWW.THEUML.COM ] reserves the right to remove from its sites any references or portfolios containing Adult Sites or Pay Sites without notice. Additionally certain links to sites, as determined from time to time by [ WWW.THEUML.COM ], or the use of links and web addresses, or the use of html formatting and scripting in certain portfolio types as determined by [ WWW.THEUML.COM ], may not be permitted within the portfolio or as an acceptable use of the personal home page link or as portfolio content.</p>
<p>[ WWW.THEUML.COM ] is under no obligation to provide exposure to competing sites through links or other methods in portfolio and may remove those at its discretion, and without notice. The [ WWW.THEUML.COM ] referral system is intended for work related offers and general inquires related to or leading to work or further discovery. Promotion of services and goods is not an appropriate use of the referral system. [ WWW.THEUML.COM ] permits one main member portfolio per person. Managers, agents, and photographers who have been authorized to post on behalf of their clients may control Model and Actor portfolios in addition to their manager, agent or photographer portfolio.</p>
<p>It is against [ WWW.THEUML.COM ] policy to allow competitor portfolio sites to solicit [ WWW.THEUML.COM ] members from an account at [ WWW.THEUML.COM ]. Any competing portfolio site or online agency site that signs up at [ WWW.THEUML.COM ] for either a free member account or a paid upgraded account, and then actively solicits [ WWW.THEUML.COM ] members to join their competing website or online agency, could have their account deactivated at [ WWW.THEUML.COM ] discretion, and without refund.</p>
<p>The Promotion and Recruitment of Escorts, Escort Services, Personal Companions, (etc.) are contrary to the purposes of [ WWW.THEUML.COM ], and will not be tolerated in any fashion. Soliciting for, recruiting, or offering the services of escorts on this site is strictly prohibited. Portfolios that are used for the solicitation or promotion of escort services in ANY way will be immediately disabled with no refund. This includes (but is not limited to): Use of the referral system, hyperlinks to external sites promoting escorts, URLs (web addresses) promoting escorts and any other activity that the staff of [ WWW.THEUML.COM ] deems as solicitations, promotions, or offers.</p>
<p>[ WWW.THEUML.COM ] has a stated policy regarding the posting of sexually explicit images to its web pages. Sexually explicit images are not permitted on this site. Sexually explicit images include but are not limited to images of sexual intercourse, obvious states of sexual arousal (erections), or overt sexual positions (such as noticeably visible or spread genitalia). Failure to adhere to this restriction will result in the removal of the images, and the disablement of that member portfolio. Consistent misclassification (rating) or categorization of images may result in the forced setting of ratings and in gross violations may result in the removal of your portfolio.</p>
<p>[ WWW.THEUML.COM ] does not support bandwidth theft, the linking of images from [ WWW.THEUML.COM ] to other sites, or the misuse of links from other sites to [ WWW.THEUML.COM ]. Anyone found linking images from [ WWW.THEUML.COM ] to other sites, copying content from [ WWW.THEUML.COM ], or inappropriately linking to [ WWW.THEUML.COM ] (to increase their views &ndash; through use of hidden frames, or using programs to artificially raise page views, etc.) will result in permanent REMOVAL from [ WWW.THEUML.COM ] without notification and may necessitate the notification of the appropriate State and/or Federal authorities.</p>
<p>You should be aware that if you voluntarily disclose personal information (e.g., user name, email address) on a bulletin board, that information can be collected and used by others and may result in unsolicited messages from other parties, and shall therefore be the sole responsibility and liability of the poster.</p>
<p>As a member of [ WWW.THEUML.COM ] &ndash; you will receive regular email updates and will be contacted by other system members seeking to work with you, and you will receive occasional email from [ WWW.THEUML.COM ]. As new features or member programs and promotions are developed and launched you will be informed via the postings to the site and also by email. We endeavor to limit email contact as much as possible from the system administrators, however when email is sent and returned with an email bad address, we will attempt to locate a correct address from any linked web site, and failing that your portfolio will be disabled. If you discover your portfolio has been disabled because of bad contact information, please contact us with the correct information and we will re-activate your portfolio.</p>
<p>This User Agreement and any disputes arising out of or related to the service and the site shall be governed by, and construed and enforced in accordance with, International laws. By your usage of, or your posting to, this site constitutes your agreement to, but not limited to, the current conditions listed in this agreement.</p>
<p>If you are 16 years or younger, you must have a parent, or a legal guardian enter and approve all information, and ensure that the parent or legal guardian&rsquo;s email address and contact information is used at all times. [ WWW.THEUML.COM ] reserves the right to change and modify these usage rules as appropriate and without notice.</p>
<p><strong>Violation of these Terms and Conditions will cause your membership to be terminated. Please Note: By signing up for any of our services you agree to be bound by all [ WWW.THEUML.COM ] terms and conditions.</strong></p>

</div>

@stop
